### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by MartaL0b0** [MartaL0b0/CILikeAPro#2]
### Explain what is this repo for
Add everything needed for the project and what the CI implies.
Define steps followed and what they do

**Comment by MartaL0b0** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fixing readme](https://trello.com/c/VqfvdCvr/1-fixing-readme)

**Comment by kikoncuo** [comment]
This is cool and dandy
